const { PrismaClient } = require('@prisma/client');
const { getRetentionDays, setRetentionDays, runRetentionCleanup } = require('../services/retentionService');
const { verifyAuditLogIntegrity, logAuditEvent } = require('../services/auditLogger');

const prisma = new PrismaClient();

/**
 * GET /api/settings — Fetch security settings, MFA adoption rate, and audit integrity (Admin only)
 */
async function getSettings(req, res) {
  try {
    const retentionDays = await getRetentionDays();

    // MFA Adoption Metrics
    const totalActiveUsers = await prisma.user.count({ where: { isActive: true } });
    const mfaUsers = await prisma.user.count({ where: { isActive: true, mfaEnabled: true } });
    const mfaAdoptionRate = totalActiveUsers > 0 ? Math.round((mfaUsers / totalActiveUsers) * 100) : 0;

    // SSO Configuration status
    const googleEnabled = Boolean(process.env.GOOGLE_CLIENT_ID);
    const microsoftEnabled = Boolean(process.env.MICROSOFT_CLIENT_ID);

    // Audit Log Integrity Verification
    const auditIntegrity = await verifyAuditLogIntegrity();

    return res.json({
      retentionDays,
      mfaMetrics: {
        totalActiveUsers,
        mfaUsers,
        mfaAdoptionRate,
      },
      ssoStatus: {
        googleEnabled,
        microsoftEnabled,
      },
      auditIntegrity,
    });
  } catch (err) {
    console.error('[getSettings]', err);
    return res.status(500).json({ error: 'Failed to fetch settings.' });
  }
}

/**
 * PUT /api/settings — Update security settings e.g. retention_days (Admin only)
 */
async function updateSettings(req, res) {
  try {
    const { retentionDays } = req.body;

    if (retentionDays !== undefined) {
      const days = parseInt(retentionDays, 10);
      if (isNaN(days) || days < 1) {
        return res.status(400).json({ error: 'Retention days must be a positive integer.' });
      }
      await setRetentionDays(days);

      await logAuditEvent({
        userId: req.user.userId,
        userEmail: req.user.email,
        action: 'retention_policy_updated',
        entityType: 'Setting',
        details: { retentionDays: days },
      });
    }

    return res.json({ message: 'Settings updated successfully.' });
  } catch (err) {
    console.error('[updateSettings]', err);
    return res.status(500).json({ error: 'Failed to update settings.' });
  }
}

/**
 * POST /api/settings/verify-audit — Trigger on-demand audit hash chain verification (Admin only)
 */
async function triggerAuditVerification(req, res) {
  try {
    const auditIntegrity = await verifyAuditLogIntegrity();

    await logAuditEvent({
      userId: req.user.userId,
      userEmail: req.user.email,
      action: 'audit_integrity_verified',
      entityType: 'Setting',
      details: { isIntact: auditIntegrity.isIntact, totalChecked: auditIntegrity.totalChecked },
    });

    return res.json({ auditIntegrity });
  } catch (err) {
    console.error('[triggerAuditVerification]', err);
    return res.status(500).json({ error: 'Failed to verify audit log integrity.' });
  }
}

/**
 * POST /api/settings/run-retention — Manually execute retention log cleanup (Admin only)
 */
async function triggerRetentionCleanup(req, res) {
  try {
    const result = await runRetentionCleanup();

    await logAuditEvent({
      userId: req.user.userId,
      userEmail: req.user.email,
      action: 'retention_cleanup_executed',
      entityType: 'Setting',
      details: result,
    });

    return res.json(result);
  } catch (err) {
    console.error('[triggerRetentionCleanup]', err);
    return res.status(500).json({ error: 'Failed to execute retention cleanup.' });
  }
}

/**
 * GET /api/settings/compliance-report — Export auditor-ready compliance summary CSV (Admin only)
 */
async function downloadComplianceReport(req, res) {
  try {
    const retentionDays = await getRetentionDays();
    const totalUsers = await prisma.user.count();
    const activeUsers = await prisma.user.count({ where: { isActive: true } });
    const adminUsers = await prisma.user.count({ where: { role: 'admin' } });
    const viewerUsers = await prisma.user.count({ where: { role: 'viewer' } });
    const mfaUsers = await prisma.user.count({ where: { isActive: true, mfaEnabled: true } });
    const mfaRate = activeUsers > 0 ? Math.round((mfaUsers / activeUsers) * 100) : 0;
    const auditIntegrity = await verifyAuditLogIntegrity();
    const totalAuditLogs = await prisma.auditLog.count();

    const timestamp = new Date().toISOString();

    const reportLines = [
      'SHADOW AI & VENDOR RISK SCANNER — ENTERPRISE COMPLIANCE & AUDIT SUMMARY',
      `Generated At: ${timestamp}`,
      `Generated By: ${req.user.email}`,
      '------------------------------------------------------------------------',
      'SECTION 1: ROLE-BASED ACCESS CONTROL (RBAC) GOVERNANCE',
      `Total Registered Accounts: ${totalUsers}`,
      `Active Accounts: ${activeUsers}`,
      `Admin Privileged Roles: ${adminUsers}`,
      `Viewer Read-Only Roles: ${viewerUsers}`,
      `Write Route Application Protection: ACTIVE (Enforced via requireAdmin Middleware)`,
      '------------------------------------------------------------------------',
      'SECTION 2: CRYPTOGRAPHIC AUDIT LOG & IMMUTABILITY',
      `Total Logged Audit Events: ${totalAuditLogs}`,
      `Application Layer Immutability: ENFORCED (No UPDATE/DELETE routes exist)`,
      `SHA-256 Hash Chain Integrity: ${auditIntegrity.isIntact ? 'VERIFIED INTACT (100% Unbroken Chain)' : 'COMPROMISED DETECTED'}`,
      `Total Logs Cryptographically Verified: ${auditIntegrity.totalChecked}`,
      `Compromised / Tampered Entries Found: ${auditIntegrity.compromisedCount}`,
      '------------------------------------------------------------------------',
      'SECTION 3: RETENTION & PURGE POLICY',
      `Configured Log Retention Period: ${retentionDays} Days`,
      `Scheduled Purge Execution: AUTOMATED (Deletes only logs older than ${retentionDays} days)`,
      '------------------------------------------------------------------------',
      'SECTION 4: AUTHENTICATION HARDENING & ENCRYPTION AT REST',
      `MFA Adoption Rate: ${mfaRate}% (${mfaUsers} of ${activeUsers} active accounts)`,
      `Session Revocation on Deactivation: ACTIVE (tokensInvalidBefore timestamp verification)`,
      `At-Rest Data Encryption: AES-256-GCM (MFA Secrets & Backup Codes Encrypted)`,
      `Password Hashing Standard: bcrypt (Cost Factor 12)`,
      '------------------------------------------------------------------------',
      'END OF COMPLIANCE REPORT',
    ].join('\n');

    res.setHeader('Content-Type', 'text/plain');
    res.setHeader('Content-Disposition', `attachment; filename="enterprise-compliance-report-${Date.now()}.txt"`);
    return res.send(reportLines);
  } catch (err) {
    console.error('[downloadComplianceReport]', err);
    return res.status(500).json({ error: 'Failed to generate compliance report.' });
  }
}

module.exports = {
  getSettings,
  updateSettings,
  triggerAuditVerification,
  triggerRetentionCleanup,
  downloadComplianceReport,
};
